import {
  TrafficIntersection,
  PJUNode,
  PedestrianCrossing,
  AirQualityData,
  IoTDevice,
  AutomationRule,
  SystemAlert,
  SystemEventLog,
  SimulationScenario,
} from '@/types/iot';

export const INITIAL_INTERSECTIONS: TrafficIntersection[] = [
  {
    id: 'TRF-01',
    name: 'Simpang Bundaran Merdeka',
    density: 64,
    vehicleCount: 1420,
    avgSpeedKmh: 34,
    queueLengthMeters: 45,
    currentLight: 'green',
    countdownSeconds: 18,
    isAutomatic: true,
    greenExtensionSeconds: 0,
    manualPhases: { red: 45, yellow: 5, green: 35 },
    emergencyPriorityActive: false,
    statusText: 'SEDANG',
  },
  {
    id: 'TRF-02',
    name: 'Simpang Veteran Utara',
    density: 78,
    vehicleCount: 2180,
    avgSpeedKmh: 18,
    queueLengthMeters: 120,
    currentLight: 'green',
    countdownSeconds: 22,
    isAutomatic: true,
    greenExtensionSeconds: 20,
    manualPhases: { red: 50, yellow: 5, green: 40 },
    emergencyPriorityActive: false,
    statusText: 'MACET TOTAL',
  },
  {
    id: 'TRF-03',
    name: 'Simpang Gatot Subroto',
    density: 42,
    vehicleCount: 890,
    avgSpeedKmh: 48,
    queueLengthMeters: 15,
    currentLight: 'red',
    countdownSeconds: 14,
    isAutomatic: true,
    greenExtensionSeconds: 0,
    manualPhases: { red: 40, yellow: 5, green: 30 },
    emergencyPriorityActive: false,
    statusText: 'LANCAR',
  },
  {
    id: 'TRF-04',
    name: 'Simpang Boulevard Sudirman',
    density: 58,
    vehicleCount: 1250,
    avgSpeedKmh: 38,
    queueLengthMeters: 30,
    currentLight: 'yellow',
    countdownSeconds: 3,
    isAutomatic: true,
    greenExtensionSeconds: 0,
    manualPhases: { red: 45, yellow: 5, green: 35 },
    emergencyPriorityActive: false,
    statusText: 'SEDANG',
  },
];

export const INITIAL_PJU_NODES: PJUNode[] = [
  {
    id: 'PJU-001',
    name: 'PJU Merdeka Tiang 01',
    location: 'Jl. Merdeka Barat No. 12',
    brightness: 68,
    powerWatts: 42,
    status: 'optimal',
    motionDetected: true,
    isAutomatic: true,
    coordinates: { x: 22, y: 35 },
    lastMotionTime: '10s lalu',
  },
  {
    id: 'PJU-002',
    name: 'PJU Merdeka Tiang 02',
    location: 'Jl. Merdeka Barat No. 44',
    brightness: 30,
    powerWatts: 18,
    status: 'energy_saving',
    motionDetected: false,
    isAutomatic: true,
    coordinates: { x: 30, y: 38 },
    lastMotionTime: '3m lalu',
  },
  {
    id: 'PJU-003',
    name: 'PJU Simpang Veteran 01',
    location: 'Jl. Veteran Akses Utara',
    brightness: 100,
    powerWatts: 60,
    status: 'optimal',
    motionDetected: true,
    isAutomatic: true,
    coordinates: { x: 65, y: 25 },
    lastMotionTime: '2s lalu',
  },
  {
    id: 'PJU-004',
    name: 'PJU Simpang Veteran 02',
    location: 'Jl. Veteran Depan RSUD',
    brightness: 100,
    powerWatts: 60,
    status: 'optimal',
    motionDetected: true,
    isAutomatic: true,
    coordinates: { x: 72, y: 30 },
    lastMotionTime: '1s lalu',
  },
  {
    id: 'PJU-005',
    name: 'PJU Techno Park 01',
    location: 'Kawasan Smart Techno A',
    brightness: 30,
    powerWatts: 18,
    status: 'energy_saving',
    motionDetected: false,
    isAutomatic: true,
    coordinates: { x: 45, y: 70 },
    lastMotionTime: '8m lalu',
  },
  {
    id: 'PJU-006',
    name: 'PJU Techno Park 02',
    location: 'Kawasan Smart Techno B',
    brightness: 30,
    powerWatts: 18,
    status: 'energy_saving',
    motionDetected: false,
    isAutomatic: true,
    coordinates: { x: 55, y: 74 },
    lastMotionTime: '12m lalu',
  },
  {
    id: 'PJU-007',
    name: 'PJU Gatot Subroto 01',
    location: 'Jl. Gatot Subroto Flyover',
    brightness: 80,
    powerWatts: 48,
    status: 'optimal',
    motionDetected: true,
    isAutomatic: true,
    coordinates: { x: 80, y: 65 },
    lastMotionTime: '5s lalu',
  },
  {
    id: 'PJU-008',
    name: 'PJU Boulevard Selatan',
    location: 'Jl. Sudirman Boulevard',
    brightness: 30,
    powerWatts: 18,
    status: 'energy_saving',
    motionDetected: false,
    isAutomatic: true,
    coordinates: { x: 20, y: 80 },
    lastMotionTime: '15m lalu',
  },
];

export const INITIAL_PEDESTRIAN_CROSSINGS: PedestrianCrossing[] = [
  {
    id: 'PED-01',
    location: 'Pelican Crossing SMAN 1 & Alun-Alun',
    pedestrianCount: 342,
    waitingCount: 24,
    status: 'HIGH ACTIVITY',
    pelicanState: 'WALK',
    countdownSeconds: 12,
    autoTriggerThreshold: 20,
    isTriggered: true,
  },
  {
    id: 'PED-02',
    location: 'Pelican Crossing Mall & Stasiun Kota',
    pedestrianCount: 185,
    waitingCount: 6,
    status: 'NORMAL',
    pelicanState: 'WAIT',
    countdownSeconds: 28,
    autoTriggerThreshold: 20,
    isTriggered: false,
  },
];

export const INITIAL_AIR_QUALITY: AirQualityData = {
  id: 'AQI-ZONE-CENTRAL',
  zone: 'Kota Pusat & Kawasan Industri',
  aqi: 72,
  pm25: 38.5,
  co: 1.8,
  co2: 418,
  no2: 24.2,
  temperature: 29.4,
  humidity: 68,
  status: 'Moderate',
  mitigationActive: false,
  mistingCannonsActive: false,
  trafficDiversionRecommended: false,
};

export const INITIAL_IOT_DEVICES: IoTDevice[] = [
  {
    id: 'ESP32-001',
    name: 'ESP32 Traffic AI Cam Node A',
    type: 'Traffic Sensor',
    location: 'Simpang Bundaran Merdeka',
    status: 'Online',
    signalRssi: 98,
    isMainsPowered: true,
    lastPing: '2s lalu',
    ipAddress: '192.168.10.101',
    mqttTopic: 'urbanpulse/traffic/simpang-merdeka',
    firmwareVersion: 'v2.4.1-smk',
    coordinates: { x: 25, y: 35 },
  },
  {
    id: 'ESP32-002',
    name: 'ESP32 PJU Adaptive Cluster Master',
    type: 'PJU Sensor',
    location: 'Jl. Merdeka Barat PJU-01',
    status: 'Online',
    signalRssi: 94,
    isMainsPowered: true,
    lastPing: '3s lalu',
    ipAddress: '192.168.10.102',
    mqttTopic: 'urbanpulse/pju/cluster-merdeka',
    firmwareVersion: 'v2.1.0-smk',
    coordinates: { x: 30, y: 38 },
  },
  {
    id: 'ESP32-003',
    name: 'ESP32 Multi-Gas Air Station',
    type: 'Air Sensor',
    location: 'Kawasan Industri Timur',
    status: 'Warning',
    signalRssi: 71,
    isMainsPowered: true,
    lastPing: '5s lalu',
    ipAddress: '192.168.10.103',
    mqttTopic: 'urbanpulse/air/zone-east',
    firmwareVersion: 'v1.9.8-smk',
    coordinates: { x: 82, y: 22 },
  },
  {
    id: 'ESP32-004',
    name: 'ESP32 Radar Pelican Controller',
    type: 'Pedestrian Radar',
    location: 'Pelican Crossing SMAN 1',
    status: 'Online',
    signalRssi: 96,
    isMainsPowered: true,
    lastPing: '1s lalu',
    ipAddress: '192.168.10.104',
    mqttTopic: 'urbanpulse/pedestrian/sman1',
    firmwareVersion: 'v2.3.0-smk',
    coordinates: { x: 40, y: 48 },
  },
  {
    id: 'ESP32-005',
    name: 'ESP32 Urban Core Gateway LoRa',
    type: 'IoT Gateway',
    location: 'Menara Komunikasi Smart City',
    status: 'Online',
    signalRssi: 100,
    isMainsPowered: true,
    lastPing: '1s lalu',
    ipAddress: '192.168.10.1',
    mqttTopic: 'urbanpulse/gateway/core',
    firmwareVersion: 'v3.0.0-smk',
    coordinates: { x: 50, y: 50 },
  },
  {
    id: 'ESP32-006',
    name: 'ESP32 PJU Cluster South',
    type: 'PJU Sensor',
    location: 'Jl. Sudirman Boulevard',
    status: 'Online',
    signalRssi: 88,
    isMainsPowered: true,
    lastPing: '4s lalu',
    ipAddress: '192.168.10.106',
    mqttTopic: 'urbanpulse/pju/cluster-south',
    firmwareVersion: 'v2.1.0-smk',
    coordinates: { x: 20, y: 80 },
  },
  {
    id: 'ESP32-007',
    name: 'ESP32 Traffic Flow Radar',
    type: 'Traffic Sensor',
    location: 'Simpang Veteran Utara',
    status: 'Online',
    signalRssi: 92,
    isMainsPowered: true,
    lastPing: '2s lalu',
    ipAddress: '192.168.10.107',
    mqttTopic: 'urbanpulse/traffic/simpang-veteran',
    firmwareVersion: 'v2.4.1-smk',
    coordinates: { x: 65, y: 25 },
  },
  {
    id: 'ESP32-008',
    name: 'ESP32 Air Quality Station Residential',
    type: 'Air Sensor',
    location: 'Kawasan Pemukiman Asri',
    status: 'Online',
    signalRssi: 85,
    isMainsPowered: true,
    lastPing: '6s lalu',
    ipAddress: '192.168.10.108',
    mqttTopic: 'urbanpulse/air/zone-residential',
    firmwareVersion: 'v1.9.8-smk',
    coordinates: { x: 42, y: 72 },
  },
];

export const INITIAL_AUTOMATION_RULES: AutomationRule[] = [
  {
    id: 'RULE-01',
    title: 'Adaptive Traffic Signal Control (ATSC)',
    description: 'Menyesuaikan durasi lampu hijau secara dinamis saat kepadatan lalu lintas melampaui batas aman.',
    triggerCategory: 'traffic',
    ifConditionText: 'Kepadatan Lalu Lintas > 70%',
    thenActionText: 'Perpanjang Lampu Hijau +20 Detik secara otomatis',
    isEnabled: true,
    thresholdValue: 70,
    thresholdUnit: '%',
    lastTriggered: '13:42:06',
    triggerCount: 38,
  },
  {
    id: 'RULE-02',
    title: 'Adaptive PJU Energy Optimization',
    description: 'Penerangan jalan meredup saat sepi dan otomatis terang 100% ketika sensor mendeteksi objek bergerak.',
    triggerCategory: 'lighting',
    ifConditionText: 'Mode Malam = TRUE DAN Gerakan Terdeteksi = TRUE',
    thenActionText: 'Naikkan Intensitas PJU ke 100% (Soft brightening)',
    isEnabled: true,
    thresholdValue: 30,
    thresholdUnit: '% baseline',
    lastTriggered: '13:45:12',
    triggerCount: 142,
  },
  {
    id: 'RULE-03',
    title: 'Smart Pelican Pedestrian Priority',
    description: 'Otomatis memberikan sinyal penyeberangan aman saat antrean pejalan kaki memenuhi kuota aman.',
    triggerCategory: 'pedestrian',
    ifConditionText: 'Jumlah Antrean Pejalan Kaki > 20 Orang',
    thenActionText: 'Aktifkan Lampu Pelican Hijau & Hentikan Lalu Lintas Kendaraan',
    isEnabled: true,
    thresholdValue: 20,
    thresholdUnit: 'orang',
    lastTriggered: '13:40:15',
    triggerCount: 19,
  },
  {
    id: 'RULE-04',
    title: 'Air Quality Emergency Mitigation',
    description: 'Mengaktifkan sistem misting cannon perkotaan dan rekayasa jalur saat polusi udara memasuki level tidak sehat.',
    triggerCategory: 'air',
    ifConditionText: 'Indeks Standar Pencemar Udara (AQI) > 100',
    thenActionText: 'Nyalakan Urban Misting Cannon & Rekomendasi Reroute Kendaraan Berat',
    isEnabled: true,
    thresholdValue: 100,
    thresholdUnit: 'AQI',
    lastTriggered: '11:15:00',
    triggerCount: 3,
  },
  {
    id: 'RULE-05',
    title: 'Idle Road Streetlight Dimming',
    description: 'Mengurangi konsumsi daya listrik PJU secara bertahap saat jalanan kosong tanpa aktivitas.',
    triggerCategory: 'lighting',
    ifConditionText: 'Jalan Kosong > 3 Menit',
    thenActionText: 'Soft Dimming PJU ke 30% (Hemat Energi 65%)',
    isEnabled: true,
    thresholdValue: 3,
    thresholdUnit: 'menit',
    lastTriggered: '13:38:00',
    triggerCount: 88,
  },
];

export const INITIAL_ALERTS: SystemAlert[] = [
  {
    id: 'ALT-101',
    timestamp: '13:42:06',
    severity: 'WARNING',
    subsystem: 'Traffic ATSC',
    location: 'Simpang Veteran Utara',
    sensor: 'ESP32-007 (Radar)',
    title: 'Kepadatan Lalu Lintas Melebihi 70%',
    description: 'Kepadatan mencapai 78% dengan panjang antrean 120 meter.',
    systemResponse: 'ATSC otomatis memperpanjang fase lampu hijau +20 detik.',
    isRead: false,
    isAcknowledged: false,
    isResolved: false,
  },
  {
    id: 'ALT-102',
    timestamp: '13:35:20',
    severity: 'CRITICAL',
    subsystem: 'Air Quality',
    location: 'Kawasan Industri Timur',
    sensor: 'ESP32-003 (Gas Array)',
    title: 'Lonjakan Partikulat PM2.5 di Zona Industri',
    description: 'Sensor mendeteksi peningkatan partikulat emisi cerobong pabrik.',
    systemResponse: 'Sistem menyarankan pengaktifan misting cannon dan pemantauan berkala.',
    isRead: false,
    isAcknowledged: true,
    isResolved: false,
  },
  {
    id: 'ALT-103',
    timestamp: '13:28:11',
    severity: 'INFO',
    subsystem: 'Smart Lighting',
    location: 'Jl. Merdeka Barat PJU-01',
    sensor: 'ESP32-002 (PIR/Radar)',
    title: 'PJU Berubah ke 100% Otomatis',
    description: 'Gerakan konvoi kendaraan terdeteksi pada segmen jalan.',
    systemResponse: 'Intensitas cahaya ditingkatkan seketika demi keamanan pengendara.',
    isRead: true,
    isAcknowledged: true,
    isResolved: true,
  },
];

export const INITIAL_EVENT_LOGS: SystemEventLog[] = [
  {
    id: 'LOG-001',
    timestamp: '13:42:05',
    subsystem: 'Traffic',
    event: 'Traffic density reached 74%',
    details: 'Simpang Veteran Utara volume spike detected',
    type: 'SYSTEM',
  },
  {
    id: 'LOG-002',
    timestamp: '13:42:06',
    subsystem: 'Automation',
    event: 'ATSC automation triggered',
    details: 'Rule 01 executed: Green light extended +20 sec',
    type: 'AUTO',
  },
  {
    id: 'LOG-003',
    timestamp: '13:40:15',
    subsystem: 'Pedestrian',
    event: 'Pelican crossing activated',
    details: 'Pedestrian count reached 24 people at SMAN 1 crossing',
    type: 'AUTO',
  },
  {
    id: 'LOG-004',
    timestamp: '13:38:00',
    subsystem: 'Lighting',
    event: 'PJU soft dimming active',
    details: 'PJU-005 & PJU-006 lowered to 30% after 3 min inactivity',
    type: 'AUTO',
  },
  {
    id: 'LOG-005',
    timestamp: '13:30:12',
    subsystem: 'IoT Gateway',
    event: 'Gateway heartbeat ping verified',
    details: 'All 8 ESP32 sensor nodes telemetry packet received',
    type: 'SYSTEM',
  },
];
